-- ============================================================================
-- Migration 010: Leave page space for heartbeat updates
-- ============================================================================
--
-- The nodes table carries 11 indexes and receives an update per heartbeat. None of
-- the columns a heartbeat writes -- tx_bytes, rx_bytes, cpu_usage_pct,
-- memory_usage_pct, battery_pct, last_heartbeat -- is indexed, so PostgreSQL can use
-- a HOT update and skip index maintenance entirely.
--
-- It can only do that when the new row version fits on the same page as the old one,
-- and the default fillfactor of 100 leaves no room. Every heartbeat therefore wrote
-- a new version on another page and touched all 11 indexes to point at it.
--
-- Measured on this PostgreSQL instance with a table of the same shape -- 5,000 rows,
-- three indexes untouched by the update, six full passes updating only unindexed
-- columns:
--
--   fillfactor 100:      0 HOT updates out of 30,000   (0.0%)   4104 kB
--   fillfactor  70:  9,718 HOT updates out of 30,000  (32.4%)   4176 kB
--
-- Zero, not merely fewer: with no free space every update relocated the row version
-- and touched every index. The storage cost was 1.8%, because most of the size here
-- is indexes rather than heap.
--
-- The real-world ratio should exceed 32%: that measurement rewrote every row six
-- times in immediate succession, which exhausts the free space faster than heartbeats
-- arriving 15 seconds apart with autovacuum reclaiming in between.
--
-- This only affects pages written after it. Existing pages keep their current
-- packing until they are rewritten, which VACUUM FULL would force -- deliberately not
-- done here, because it takes an exclusive lock on the table.

ALTER TABLE nodes SET (fillfactor = 70);
