{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neronet.secretName" . }}
  labels:
    {{- include "neronet.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | default (randAlphaNum 64) | quote }}
  refresh-secret: {{ .Values.secrets.refreshSecret | default (randAlphaNum 64) | quote }}
  admin-password: {{ .Values.secrets.adminPassword | default (randAlphaNum 32) | quote }}
  registration-token: {{ .Values.secrets.registrationToken | default (randAlphaNum 48) | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | default (randAlphaNum 32) | quote }}
{{- end }}
