apiVersion: v1
kind: Service
metadata:
  name: {{ include "neronet.fullname" . }}
  labels:
    {{- include "neronet.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: console
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: api
  selector:
    {{- include "neronet.selectorLabels" . | nindent 4 }}
