#!/bin/sh
# Usage: gen-env.sh [path]
#
# Writes a .env file with fresh random values for every secret the compose stack
# requires. Default path: <repo>/.env. Refuses to overwrite an existing file, so a
# stack's database password can never be replaced by accident. The values are never
# printed; read them from the file.
set -eu
. "$(dirname "$0")/engine.sh"

TARGET=${1:-$REPO_ROOT/.env}

# Hex characters only: safe in a compose .env file and inside a connection URL.
rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  else
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

umask 077

# noclobber makes the redirection fail if the file already exists, and the check and
# the creation are one step, so two runs cannot both succeed.
if ! (set -C; : > "$TARGET") 2>/dev/null; then
  die "$TARGET already exists; remove it first if you want new secrets"
fi

{
  echo "# Generated by scripts/dev/gen-env.sh. Local development only."
  echo "POSTGRES_PASSWORD=$(rand_hex 24)"
  echo "SOVEREIGN_JWT_SECRET=$(rand_hex 32)"
  echo "SOVEREIGN_REFRESH_SECRET=$(rand_hex 32)"
  echo "SOVEREIGN_ADMIN_PASS=$(rand_hex 16)"
  echo "SOVEREIGN_REGISTRATION_TOKEN=$(rand_hex 32)"
} > "$TARGET"

# No effect on filesystems without POSIX modes (NTFS through Git Bash).
chmod 600 "$TARGET" 2>/dev/null || true

echo "wrote $TARGET (5 secrets, not shown)"
