package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/invopop/jsonschema"
	"github.com/sovereign/proxy/v4/pkg/control"
)

type typeEntry struct {
	Name     string
	Instance any
}

func main() {
	outDir := flag.String("out", "api/contract/v4", "Output directory for JSON schemas")
	flag.Parse()

	if err := os.MkdirAll(*outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "failed to create output dir: %v\n", err)
		os.Exit(1)
	}

	entries := []typeEntry{
		{Name: "ChallengeRequest", Instance: &control.ChallengeRequest{}},
		{Name: "ChallengeResponse", Instance: &control.ChallengeResponse{}},
		{Name: "RegisterRequest", Instance: &control.RegisterRequest{}},
		{Name: "RegisterResponse", Instance: &control.RegisterResponse{}},
		{Name: "HeartbeatRequest", Instance: &control.HeartbeatRequest{}},
		{Name: "HeartbeatResponse", Instance: &control.HeartbeatResponse{}},
		{Name: "DiscoverRequest", Instance: &control.DiscoverRequest{}},
		{Name: "DiscoverResponse", Instance: &control.DiscoverResponse{}},
		{Name: "CircuitRequest", Instance: &control.CircuitRequest{}},
		{Name: "CircuitResponse", Instance: &control.CircuitResponse{}},
		{Name: "ACLSyncRequest", Instance: &control.ACLSyncRequest{}},
		{Name: "ACLSyncResponse", Instance: &control.ACLSyncResponse{}},
		{Name: "RouteSyncRequest", Instance: &control.RouteSyncRequest{}},
		{Name: "RouteSyncResponse", Instance: &control.RouteSyncResponse{}},
		{Name: "NetmapRequest", Instance: &control.NetmapRequest{}},
		{Name: "NetmapResponse", Instance: &control.NetmapResponse{}},
	}

	for _, entry := range entries {
		r := &jsonschema.Reflector{
			ExpandedStruct: true,
			Anonymous:      true,
		}

		schema := r.Reflect(entry.Instance)
		schema.Comments = "DO NOT EDIT. Generated by 'go run ./cmd/contractgen' from Go struct tags in pkg/control/types.go."

		if schema.Definitions != nil {
			if def, ok := schema.Definitions["EndpointDesc"]; ok {
				objDef := &jsonschema.Schema{
					Type:                 "object",
					Properties:           def.Properties,
					Required:             []string{"ip_address", "port"},
					AdditionalProperties: jsonschema.FalseSchema,
				}
				schema.Definitions["EndpointDesc"] = &jsonschema.Schema{
					OneOf: []*jsonschema.Schema{
						objDef,
						{Type: "string"},
					},
				}
			}
		}

		// Customize any specific schema properties if needed
		data, err := json.MarshalIndent(schema, "", "  ")
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to marshal schema for %s: %v\n", entry.Name, err)
			os.Exit(1)
		}

		filePath := filepath.Join(*outDir, fmt.Sprintf("%s.schema.json", entry.Name))
		// Append newline
		data = append(data, '\n')
		if err := os.WriteFile(filePath, data, 0644); err != nil {
			fmt.Fprintf(os.Stderr, "failed to write schema to %s: %v\n", filePath, err)
			os.Exit(1)
		}
		fmt.Printf("Generated %s\n", filePath)
	}
}
